pwatson100/symbaroum

script/common/migration.js
Migrating all actor data correctly.
=> Migration fix

Release_Notes.txt, script/common/migration.js, system.json
Bring NewDev in line with master.
=> Bring NewDev in line with master.

script/common/dialog.js, script/common/roll.js, script/sheet/player.js
This is to allow separate character sheets and rolls for familiars etc.
=> Made sure character is displayed when rolling

lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/handlebars.js, script/common/hooks.js, script/common/item.js, script/common/roll.js, template/chat/applyEffectsButton.html
A lot of stuff!
abilities and powers list in EN and FR
new simplified roll function
modified dialog for roll
chat template for presenting abilities and power results
auto-apply damage, healing, status with a GM button + hook.
Bend will, curse, medicus and loremaster are done in FR and EN.
=> automatize effects and damage, comments

script/common/dialog.js, template/chat/dialog.html
Small fix to resolve impeding dialogue issues after merge.
=> Fix for impeding in dialogue.

script/sheet/monster.js
Monster sheet width in Monster.js increased to 800px in line with the… Player sheet.
=> Monster sheet width in Monster.js increased to 800px 

lang/sv.json
=> Swedish Language updates

script/common/item.js
- print target token name rather than target actor name
- in auto combat, use selected token name rather than actor name
=> get token name in combat

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/actor.js, script/common/dialog.js, script/common/hooks.js, script/common/item.js, script/common/roll.js, template/chat/dialog.html
Refactoring of the dialogue
Show attribute modifiers (and system setting)
=> Support for Massive

script/common/actor.js, script/common/dialog.js, template.json, template/chat/dialog.html, template/sheet/tab/player2-main.html
Template.json fix for adding weapons on the character sheet
Added briefer damage to show on the character sheet
Added tooltip damage to show what is included in the damage roll in the roll dialogue.
=> Minor fixes and re-arrangements.

template/chat/roll.html
=> Fix for #112

script/common/migration.js, system.json, template.json
attribute.total in template
New version and new template version
=> attribute.total in template

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/roll.js, template/chat/dialog.html, template/chat/roll.html
=> Cleaner roll results

script/common/migration.js, template/migration-warning.html
Warning window when migrating world to v3 template.
=> Migration warning message

msgdata/data.json
Advance push for messaging system.
=> Set-up for messaging system

script/common/actor.js, template/sheet/tab/player2-main.html
=> Fix for Defense / Attack do not display modifiers for npcs. #158

script/common/handlebars.js, script/common/item.js, template/chat/item.html, template/sheet/artifact.html
=> Post to Chat for artifacts #161

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/item.js, script/common/roll.js
=> Black bolt

script/common/actor.js
Validating that an attribute conforms to our format
=> Protection against rogue attributes, such can be introduced by modules

template/sheet/tab/player-gear.html
=> Equipment & Artifact change

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/actor.js, script/common/hooks.js, script/common/roll.js
- auto evaluation of initiative attribute
- add option for manual setting of the initiative attribute
=> Initiative attribute

lang/fr.json, script/common/hooks.js, script/common/item.js
Berserker status icon will now appear when creating a token from an actor with berserk activated.
=> Berserker icon

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/item.js, template/chat/combat.html, template/chat/dialog2.html
- Upgraded medicus related to #235 
- Weapons with Flaming quality will enflame the target token (in EC)
=> Medicus #235

script/common/actor.js, script/common/item.js, script/sheet/actor.js, script/sheet/item.js
item.data.data.script(item, actor)  to start a scripted ability (on actors'items)
=> Scripted abilities property

script/common/actor.js
"Rapid reflexes" master level : the character acts first in the round, ignoring initiative attribute.
=> Rapid reflexes master

lang/en.json, script/common/actor.js, script/common/migration.js, script/sheet/item.js, template.json
Fixes for MCE issues for when data is not comitted.
=> Fixes for mce issue

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/item.js
Warning when corruption reach threshold-1
=> Corruption warning

template/user-guide-en.html
Added note about using the Experience box.
=> Small update to the "Generating Characters" section of the user guide.

template/sheet/ability.html, template/sheet/armor.html, template/sheet/boon.html, template/sheet/burden.html, template/sheet/equipment.html, template/sheet/mystical-power.html, template/sheet/player.html, template/sheet/player2.html, template/sheet/ritual.html, template/sheet/tab/artifact.html, template/sheet/tab/bonus.html, template/sheet/tab/player-bio.html, template/sheet/tab/player-gear.html, template/sheet/tab/player2-main.html, template/sheet/trait.html, template/sheet/weapon.html, template/symbaroumSettings.html
Also homogenised the use of id / _id
=> Usuability fixes (label for)

script/common/actor.js, template/sheet/tab/player-gear.html
=> Autosort #221

script/common/item.js, script/common/roll.js
Corrected issue #254 : Ability - Backstab (master) have no effect
=> Backstab master implemented

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/sv.json, script/common/hooks.js, script/common/roll.js
=> Bithir death saves

script/common/dialog.js, script/common/hooks.js, script/common/item.js, script/common/roll.js, template/chat/item.html, template/chat/roll.html
Normal mode - full support for Maestro #126 and use of DsN non-API #190
=> Normal mode - full support for Maestro #126 and use of DsN non-API

script/common/hooks.js
dice3d.addSystem and dice3d.addColorset needed 'preferred' rather than 'true' and 'default'.
=> DsN settings correction

item-enhance.txt, script/common/actor.js, script/common/config.js, script/common/item.js, template/sheet/boon.html, template/sheet/burden.html
Reworked secondary attributes processing : Toughness and corruption
=> Toughness and Corruption

script/common/actor.js, script/common/item.js
- Bug not using correct damage reduction when using mystic powers
=> Bug MP damage resistance

script/common/item.js
=> Fixed the stackable armor check

script/common/item.js
Also removed automatic shield bonus
=> Bithir qucikfixes

script/common/hooks.js, script/common/item.js
- bug when bleeding / burning icons were stayed stucked on token
=> Bleeding icon bug

script/common/dialog.js, template/chat/ability.html
=> Minor bugfixes

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/it.json, lang/sv.json, script/common/config.js, script/common/dialog.js, script/common/hooks.js, script/common/item.js, template/user-guide-en.html
=> Witch hammer

lang/de.json, lang/en.json, script/common/handlebars.js, script/common/hooks.js, script/common/item.js, script/common/macro.js, script/common/migration.js, script/sheet/actor.js, script/sheet/item.js, script/sheet/player2.js, template/chat/item.html, template/sheet/ability.html, template/sheet/armor.html, template/sheet/artifact.html, template/sheet/boon.html, template/sheet/burden.html, template/sheet/equipment.html, template/sheet/mystical-power.html, template/sheet/ritual.html, template/sheet/tab/artifact.html, template/sheet/tab/player-bio.html, template/sheet/tab/player-note.html, template/sheet/trait.html, template/sheet/weapon.html
=> Migration and mce fixes

system.json
Verified is required - not sure if this will go away once we have it live.
=> Bithir v10work

template/sheet/trait.html
=> Removed errornous bracket

lang/de.json
=> Fixed corrupt de.json file

script/common/actor.js, script/common/dialog.js, script/common/item.js
Cherrypicked the commit from #608 to RT-V10 as requested.
=> prepareRollAttribute resolves when roll completes

script/common/hooks.js, script/common/item.js
Fix on Blessed Shield item creation & automatically delete token Blessed Shield when status effect off.
=> Blessed Shield EC fixed

script/common/hooks.js, script/common/item.js
modifyEffectOnToken was asynchronous and seems to crash with createBlessedShield, so effect was not visible but not really stored
=> fix synchronicity modifyEffectOnToken

lang/de.json
de.json now has the same structure / lines as en.json, except the Symbaroum System Tour
=> German Translation for 4.3.2

Release_Notes.txt, script/common/dialog.js, system.json
=> Advantage calculations fails in v13

Release_Notes.txt, script/common/devmsg.js, script/common/enricher.js, src/packs/systemuserguides/journal_Symbaroum_System_guide_EN_sSZzEbMgSLEclyBL.json, system.json
Also, added prevention of loading external content via @RAW.
=> Minor fixes for when Foundry runs under different path and not the root of the webserver
